import type { Metadata } from 'next';
import '@/app/globals.scss';
import { CopyToClipboardContextProvider } from '@/components/context/CopyContextProvider';
import { SnackbarContextProvider } from '@/components/context/SnackbarContextProvider';
import { CommonLayout } from '@/components/layout/CommonLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = (props: RootLayoutProps) => (
  <html lang="ja">
    <body>
      <SnackbarContextProvider>
        <CopyToClipboardContextProvider>
          <CommonLayout>{props.children}</CommonLayout>
        </CopyToClipboardContextProvider>
      </SnackbarContextProvider>
    </body>
  </html>
);

export default RootLayout;
