import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { CommonLayout } from "@/components/layout/CommonLayout";
import { SnackbarContextProvider } from "@/components/context/SnackbarContextProvider";
import { CopyToClipboardContextProvider } from "@/components/context/CopyContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout = (props: RootLayoutProps) => (
  <html lang="ja">
    <body>
      <SnackbarContextProvider>
        <CopyToClipboardContextProvider>
          <CommonLayout>{props.children}</CommonLayout>
        </CopyToClipboardContextProvider>
      </SnackbarContextProvider>
    </body>
  </html>
);

export default RootLayout;
